[package]
name = "convex"
version = "0.1.0"
edition = "2021"

build = "build.rs"

[dependencies]
lalrpop-util = { version = "0.19.8", features = ["lexer"] }
regex = "1"

[build-dependencies]
lalrpop = "0.19.8"
